version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
  api:
    build:
      context: /IA-API
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
volumes:
  app_node_modules:
